services:
    para.application:
        public: true
        class: Para\Para

    para.command.execute:
        class: Para\Command\ExecuteCommand
        arguments:
            - '@logger'
            - '@para.async_shell_command_executor'
            - '@para.configuration.group_configuration'
            - '@para.buffered_output_adapter_factory'
        tags:
            - { name: console.command, command: 'execute' }

    para.command.add_project:
        class: Para\Command\AddProjectCommand
        arguments:
            - '@logger'
            - '@para.configuration.group_configuration'
            - '@para.factory.project_factory'
            - '@para.factory.project_array_decorator_factory'
        tags:
            - { name: console.command, command: 'add:project' }

    para.command.delete_group:
        class: Para\Command\DeleteGroupCommand
        arguments:
            - '@logger'
            - '@para.configuration.group_configuration'
        tags:
            - { name: console.command, command: 'delete:group' }

    para.command.delete_project:
        class: Para\Command\DeleteProjectCommand
        arguments:
            - '@logger'
            - '@para.configuration.group_configuration'
        tags:
            - { name: console.command, command: 'delete:project' }

    para.command.show_log:
        class: Para\Command\ShowLogCommand
        arguments:
            - '@logger'
            - '@para.process_factory'
            - '@para.configuration.group_configuration'
            - '%para.log_path%'
        tags:
            - { name: console.command, command: 'show:log' }
            - { name: console.command, command: 'log' }

    para.command.show_config:
        class: Para\Command\ShowConfigCommand
        arguments:
            - '@logger'
            - '@para.process_factory'
            - '%para.config%'
        tags:
            - { name: console.command, command: 'show:config' }
            - { name: console.command, command: 'config' }

    para.command.open_shell:
        class: Para\Command\OpenShellCommand
        arguments:
            - '@logger'
            - '@para.shell_factory'
            - '@para.configuration.group_configuration'
            - '%para.history%'
        tags:
            - { name: console.command, command: 'open:shell' }
            - { name: console.command, command: 'shell' }

    para.command.self_update:
        class: Para\Command\SelfUpdateCommand
        arguments:
            - '@logger'
            - '@para.application'
            - '@para.process_factory'
            - '%para.tools_path%'
        tags:
            - { name: console.command, command: 'self-update' }


