services:
    event_dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher

    para.shell_command_event_subscriber:
        class: Para\EventSubscriber\SanitizeShellCommandEventSubscriber
        tags:
            - { name: 'kernel.event_subscriber' }

    para.shell_key_press_event_subscriber:
        class: Para\EventSubscriber\ShellKeyPressEventSubscriber
        arguments:
            - '@para.history_shell_manager'
        tags:
            - { name: 'kernel.event_subscriber' }

    para.add_environment_variable_event_subscriber:
        class: Para\EventSubscriber\AddEnvironmentVariableEventSubscriber
        tags:
            - { name: 'kernel.event_subscriber' }

    para.log_process_output_event_subscriber:
        class: Para\EventSubscriber\LogProcessOutputEventSubscriber
        arguments: ['%para.log_path%']
        tags:
            - { name: 'kernel.event_subscriber' }
