parameters:
    para.root: '%bin_dir%/../'
    para.config: '%para.root%config/para.yml'
    para.log_path: '%para.root%logs/'
    para.tools_path: '%para.root%tools/'
    para.history: '%para.root%config/.para_history'

services:
    logger.streamhandler:
        class: Monolog\Handler\RotatingFileHandler
        arguments: ['%para.root%logs/para.log', 8]
        calls:
            - [setFormatter, ['@monolog.formatter.application_formatter']]

    logger:
        class: Symfony\Bridge\Monolog\Logger
        arguments:
            - 'application'
        calls:
            - [pushHandler, ['@logger.streamhandler']]
            - [pushProcessor, ['@monolog.processor.introspection_processor']]

    monolog.formatter.application_formatter:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] [%%level_name%%] [%%extra.class%%] [%%extra.function%%] %%message%% %%context%%\n"

    monolog.processor.introspection_processor:
        class: Monolog\Processor\IntrospectionProcessor

    yaml.dumper:
        class: Symfony\Component\Yaml\Dumper

    yaml.parser:
        class: Symfony\Component\Yaml\Parser

    filesystem:
        class: Symfony\Component\Filesystem\Filesystem

    composer_factory:
        class: Composer\Factory

    para.yaml.dumper:
        class: Para\Dumper\YamlDumper
        arguments: ['@yaml.dumper']

    para.yaml.parser:
        class: Para\Parser\YamlParser
        arguments: ['@yaml.parser']

    para.configuration.group_configuration:
        class: Para\Configuration\GroupConfiguration
        arguments:
            - '@para.yaml.parser'
            - '@para.yaml.dumper'
            - '@para.factory.group_factory'
            - '@para.factory.project_factory'
            - '%para.config%'
        calls:
            - [load]

    para.plugin.plugin_manager:
        class: Para\Plugin\PluginManager
        arguments:
            - '@para.factory.composite_repository_factory'
            - '@composer_factory'
            - '@para.factory.plugin_factory'
            - '@para.factory.process_factory'
            - '@para.package.stable_package_finder'
            - '%para.root%'

    para.factory.process_factory:
        public: true
        class: Para\Factory\ProcessFactory

    para.shell_factory:
        class: Para\Factory\ShellFactory
        arguments:
            - '@logger'
            - '@para.application'
            - '@para.factory.process_factory'
            - '@event_dispatcher'
            - '@para.history_shell_manager'

    para.factory.project_array_decorator_factory:
        class: Para\Factory\ProjectArrayDecoratorFactory

    para.async_shell_command_executor:
        class: Para\Service\AsyncShellCommandExecutor
        arguments: ['@para.display_strategy_factory']

    para.shell_history:
        class: Para\Service\ShellHistory

    para.history_shell_manager:
        class: Para\Service\HistoryShellManager
        arguments:
            - '@logger'
            - '@para.shell_history'

    para.package.stable_package_finder:
        class: Para\Package\StablePackageFinder

    para.display_strategy_factory:
        class: Para\Service\Strategy\DisplayStrategyFactory
        arguments: ['@para.factory.process_factory', '@event_dispatcher']

    para.buffered_output_adapter_factory:
        class: Para\Factory\BufferedOutputAdapterFactory

    para.factory.project_factory:
        class: Para\Factory\ProjectFactory

    para.factory.group_factory:
        class: Para\Factory\GroupFactory

    para.factory.table_output_factory:
        class: Para\Factory\TableOutputFactory

    para.factory.composite_repository_factory:
        class: Para\Factory\CompositeRepositoryFactory

    para.factory.plugin_factory:
        class: Para\Factory\PluginFactory
